Milestone2
alekott/shopilingus pull request #1
Opened 2018-02-09 19:59 UTC by alekott

2018-02-10 07:46 UTC, yuriyyakym requested changes
Nice code. Mostly styleguide changes are required.

2018-02-10 07:46 UTC, yuriyyakym commented on src/Shop.java
> +            if ( productDetails.product.id == productId){
Inconsistent space after a bracket.

2018-02-10 07:46 UTC, yuriyyakym commented on src/Shop.java
> +        for ( Service service : services){
Inconsistent space after bracket.

2018-02-10 07:46 UTC, yuriyyakym commented on src/ShoppingCenter.java
> +    public void updateShop(int shopId, Shop modifiedShop){
No space before curly bracket

2018-02-10 07:46 UTC, yuriyyakym commented on src/Shop.java
> +    public void updateService(int serviceId, Service modifiedService){
Same here

2018-02-10 07:46 UTC, yuriyyakym commented on src/Shop.java
> +    public Service getServiceById(int serviceId){
No space before curly bracket.

2018-02-10 07:46 UTC, yuriyyakym commented on src/ShoppingCenter.java
> +    public void deleteShop (int shopId){
same here

2018-02-10 07:46 UTC, yuriyyakym commented on src/ShoppingCenter.java
> +    public void deleteShop (int shopId){
just fix it everywhere

2018-02-10 07:46 UTC, yuriyyakym commented on src/ShoppingCenter.java
> +        return getAllProducts().stream()
Just make items of that stream unique (use `.distinct` method)

2018-02-10 07:46 UTC, yuriyyakym commented on src/Product.java
> +    public String type;
Keep public fields together.

2018-02-10 07:46 UTC, yuriyyakym commented on src/Shop.java
>      private List<Employee> employees;
keep private fields together

2018-02-10 10:00 UTC, yuriyyakym commented on src/Shop.java
> +
Redundant empty line

2018-02-10 10:00 UTC, yuriyyakym commented on src/ShoppingCenter.java
> +
redundant empty line

2018-02-27 08:07 UTC, michal-marciniec approved these changes

2018-02-27 14:10 UTC, merged